image: python:3.10.8

pipelines:
  default:
    - parallel:
      - step:
          name: Modular tests
          caches:
            - pip
          script:
            - pip install pipenv --upgrade
            - pipenv install --system
            - pytest modular_arithmetics -s -v --durations=0 --cov=.

